import React, { useState } from 'react';
import './GetDiagonosis.css';

const GetDiagnosis = () => {
  const [symptoms, setSymptoms] = useState('');
  const [diagnosis, setDiagnosis] = useState('');
  const [predictions, setPredictions] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');
    setDiagnosis('');
    setPredictions([]);
    
    try {
      const response = await fetch('http://localhost:5000/api/diagnosis', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ symptoms }),
      });
      
      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
      
      const data = await response.json();
      setDiagnosis(data.diagnosis);
      
      
    } catch (error) {
      console.error('Error fetching diagnosis:', error);
      setError('Unable to generate diagnosis. Please try again later.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleClear = () => {
    setSymptoms('');
    setDiagnosis('');
    setPredictions([]);
    setError('');
  };

  const setExampleSymptoms = (exampleText) => {
    setSymptoms(exampleText);
  };

  return (
    <div className="diagnosis-page">
      <div className="diagnosis-container">
        <h1>AI Healthcare Diagnosis</h1>
        <p>Describe your symptoms for an AI-powered preliminary diagnosis using our trained medical model.</p>
        
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="symptoms">Symptoms:</label>
            <textarea
              id="symptoms"
              value={symptoms}
              onChange={(e) => setSymptoms(e.target.value)}
              placeholder="Describe your symptoms in detail (e.g., fever and persistent cough for 3 days, difficulty breathing...)"
              rows="6"
              required
            />

          </div>
          
          {/* Quick Example Buttons */}
          <div className="example-buttons">
            <h4>Quick Examples:</h4>
            <button 
              type="button" 
              className="example-btn"
              onClick={() => setExampleSymptoms('fever, persistent cough, and difficulty breathing for 3 days')}
            >
              Respiratory Symptoms
            </button>
            <button 
              type="button" 
              className="example-btn"
              onClick={() => setExampleSymptoms('frequent urination, excessive thirst, and blurred vision')}
            >
              Metabolic Symptoms
            </button>
            <button 
              type="button" 
              className="example-btn"
              onClick={() => setExampleSymptoms('severe headache, nausea, and sensitivity to light')}
            >
              Neurological Symptoms
            </button>
            <button 
              type="button" 
              className="example-btn"
              onClick={() => setExampleSymptoms('joint pain, morning stiffness, and swelling in hands')}
            >
              Joint Symptoms
            </button>
          </div>
          
          <div className="button-group">
            <button type="submit" disabled={isLoading}>
              {isLoading ? 'Analyzing Symptoms...' : 'Get AI Diagnosis'}
            </button>
            <button type="button" onClick={handleClear}>
              Clear
            </button>
          </div>
        </form>
        
        {error && (
          <div className="error-message">
            <p>❌ {error}</p>
          </div>
        )}
        
        {diagnosis && (
          <div className="diagnosis-result">
            <h2>🏥 AI Diagnosis Results</h2>
            <div className="diagnosis-content">
              <pre className="diagnosis-text">{diagnosis}</pre>
            </div>
            <div className="disclaimer">
              <p><strong>⚠️ Important Medical Disclaimer:</strong></p>
              <p>This AI diagnosis is generated by a machine learning model trained on medical data and is intended for educational purposes only. It should NOT replace professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for proper medical evaluation and care.</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default GetDiagnosis;